# Generated by Django 3.2 on 2022-03-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='posted_by',
            field=models.CharField(max_length=40),
        ),
    ]
