# Generated by Django 3.2 on 2022-04-27 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_alter_review_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='approved',
        ),
    ]
